# Generated by Django 4.2.7 on 2023-11-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ianapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
