# Generated by Django 4.2.7 on 2023-11-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ianapp', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
