# Generated by Django 4.2.7 on 2023-11-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ianapp', '0003_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
